version: 0.2

env:
  parameter-store:
     DOCKER_REGISTRY_USERNAME: 
     DOCKER_REGISTRY_PASSWORD:
     DOCKER_REGISTRY_URL:
  phases:
     install:
       runtime-versions:
         python: 3.11
     pre_build:
       commands:
         - echo "Installing dependencies..."
         - pip install -r simple-python-app/requirements.txt
    build:
      commands:
        - echo "Running tests..."
        - cd sample-python-app/
        - echo " Building Docker image... "
        - docker build -t "<>"
        - docker push "<>"
    post_build:
      commands:
        - echo "Build completed successfully..."
        
